lambda: 2
pct: 4
num_nodes: 100000
homophily: TRUE
allies: TRUE
degree: 20
max_ticks: 400
runs: 10
support_dist: distributeSupport1988(stdev = c(.2, .2, .2, .2, .2))
network_type: do.call(sample_gnm_wrapper, args = list(nei = floor(config$degree/2)))
